export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS'
export const REQUEST_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
export const REQUEST_QUESTIONS_ERROR = 'FETCH_QUESTIONS_ERROR'

export const QUESTION_CORRECT = 'INCREMENT_SCORE'
export const QUESTION_INCORRECT = 'DECREMENT_SCORE'

export const RESTART = 'RESTART'
